name: Checks

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-checks:
    name: Run Checks
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 22

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run ESLint check
        if: always()
        run: npx eslint src/**

      - name: Run Prettier check
        if: always()
        run: npx prettier ./src/** --check

      - name: Run Tests
        if: always()
        run: npm run test
